name: curso
description: Não corra mais riscos!.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  intl: ^0.15.7
  sqflite: ^1.0.0
  path_provider: ^0.4.1
  numberpicker: ^0.1.6
  flutter_masked_text: ^0.6.0
  shared_preferences: ^0.4.2
  auto_size_text: ^0.3.0
  rxdart: ^0.20.0
  bloc_pattern: ^1.5.1
  bubble_bottom_bar: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: FiraSans
      fonts:
        - asset: fonts/FiraSans-Bold.ttf
        - asset: fonts/FiraSans-Italic.ttf
        - asset: fonts/FiraSans-Regular.ttf