name: curso
description: Não corra mais riscos!.

version: 1.0.0+1

environment:
  sdk: ">=2.4.0 <= 3.0.0"
dependencies:
  flutter:
    sdk: flutter
  helper_tiles:
    git:
      url: https://github.com/bicasoftware/helper_tiles
  lib_observer:
    git:
      url: https://github.com/bicasoftware/lib_observer

  cupertino_icons: ^0.1.2
  intl: ^0.15.8
  sqflite: ^1.1.6+4
  path_provider: ^1.2.0
  rxdart: ^0.22.2
  provider: ^3.1.0
  morpheus: ^1.2.0+6
  pie_chart: ^1.2.0
  flutter_material_color_picker: ^1.0.3
  shared_preferences: ^0.5.3+4


dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: FiraSans
      fonts:
        - asset: fonts/FiraSans-Bold.ttf
        - asset: fonts/FiraSans-Italic.ttf
        - asset: fonts/FiraSans-Regular.ttf