name: curso
description: Não corra mais riscos!.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <= 3.0.0"
dependencies:

  flutter:
    sdk: flutter
  helper_tiles:
    git:
      url: https://github.com/bicasoftware/helper_tiles
  lib_observer:
    git:
      url: https://github.com/bicasoftware/lib_observer

  dio: ^3.0.3
  cupertino_icons: ^0.1.2
  intl: ^0.15.8
  sqflite: ^1.1.7+1
  path_provider: ^1.4.0
  rxdart: ^0.22.4
  provider: ^3.1.0+1
  morpheus: ^1.2.2+1
  pie_chart: ^1.3.0
  http: ^0.12.0+2
  json_serializable: ^3.2.3
  flushbar: ^1.9.1
  flutter_secure_storage: ^3.3.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.0.0
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: FiraSans
      fonts:
        - asset: fonts/FiraSans-Bold.ttf
        - asset: fonts/FiraSans-Italic.ttf
        - asset: fonts/FiraSans-Regular.ttf