name: curso
description: Não corra mais riscos!.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2"
dependencies:
  flutter:
    sdk: flutter
  helper_tiles:
    git:
      url: https://github.com/bicasoftware/helper_tiles

  cupertino_icons: ^0.1.2
  intl: ^0.15.8
  sqflite: ^1.1.5
  path_provider: ^1.0.0
  rxdart: ^0.22.0
  bloc_provider: ^0.6.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: FiraSans
      fonts:
        - asset: fonts/FiraSans-Bold.ttf
        - asset: fonts/FiraSans-Italic.ttf
        - asset: fonts/FiraSans-Regular.ttf