name: Flutter

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build-apk:
    name: Build APK
    
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: flutter build apk --debug
      
  build-ios:
    name: Build IOS
    
    runs-on: macOS-latest
      
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: flutter build ios --no-codesign
